---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main-Debian.yml
  when: ansible_os_family == 'Debian'

- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: UTILISATEUR postgres
  include_tasks: includes/user.yml

- name: INSTALLATION DE PostgreSQL SUR UNE BASE Debian
  include_tasks: includes/setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: INSTALLATION DE PostgreSQL SUR UNE BASE RedHat
  include_tasks: includes/setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: INITIALISATION DE PostgreSQL
  include_tasks: includes/initialize.yml

- name: CONFIGURATION DE PostgreSQL
  include_tasks: includes/configure.yml

- name: RÔLE(S) DE PostgreSQL
  include_tasks: includes/roles.yml

- name: CRÉATION DES MODÈLES DE BASES DE DONNÉES PostgreSQL
  include_tasks: includes/templates.yml

- name: AJOUT DES EXTENSIONS PostgreSQL
  include_tasks: includes/extensions.yml

- name: CRÉATION DES BASES DE DONNÉES PostgreSQL
  include_tasks: includes/databases.yml

# - name: PGTune PostgreSQL
#   include_tasks: includes/pgtune.yml

# - name: REDÉMARRAGE DU SERVICE postgresql
#   ansible.builtin.systemd_service:
#     name: "{{ postgresql.daemon }}"
#     state: started
#   become: true