---
- name: RECONSTRUCTION DE LA BASE DE DONNÉES DES PARAMÈTRES RÉGIONAUX
  ansible.builtin.command: >
    dpkg-reconfigure --frontend noninteractive locales
  changed_when: true

- name: REDÉMARRAGE DU SERVICE SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true