---
- name: VÉRIFICATION DE L'EXISTENCE DU GROUPE UTILISATEUR postgres
  ansible.builtin.group:
    name: "{{ postgresql.user.name }}" 
    gid: "{{ postgresql.user.gid }}"
    state: present
  become: true

- name: AJOUT DE L'UTILISATEUR postgres
  user:
    name: "{{ postgresql.user.name }}"    
    uid: "{{ postgresql.user.uid }}"
    group: "{{ postgresql.user.gid }}"
    create_home: false
    home: "{{ postgresql.directories.home }}"
    shell: /bin/bash
    system: true
    comment: "{{ postgresql.user.comment }}"
  become: true

- name: DÉFINITION DES VARIABLES D'ENVIRONNEMENT PostgreSQL
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  become: true
