---
- hosts: geo
  tags: deployment
  gather_facts: no
  vars_files:
    - vars/vault.yml
  roles:
    - role: deployment

- hosts: geo
  tags: setup
  vars_files:
    - vars/vault.yml
  pre_tasks:
  - name: MISE À JOUR SYSTÈME
    become: true
    apt:
      update_cache: true
      upgrade: true
      cache_valid_time: 14400
  roles:
    - role: setup
    - role: postgresql
    - role: geo