---
- name: CHARGEMENT DES VARIABLES
  include_vars: defaults/main.yml

- name: CRÉATION DU CONTENEUR LXC
  proxmox:
    # proxmox_default_behavior: no_defaults
    node: "{{ proxmox.pve.api.node }}"
    api_host: "{{ proxmox.pve.api.host }}"
    api_user: "{{ proxmox.pve.api.user }}"
    api_password: "{{ proxmox.pve.api.password }}"
    api_token_id: "{{ proxmox.pve.api.token_id }}"
    api_token_secret: "{{ proxmox.pve.api.token_secret }}"
    vmid: "{{ proxmox.lxc.vmid }}"
    cores: "{{ proxmox.lxc.cores }}"
    cpus: "{{ proxmox.lxc.cpus }}"
    cpuunits: "{{ proxmox.lxc.cpuunits }}"
    description: |
      {{ proxmox.lxc.description }}
    disk: "{{ proxmox.lxc.disk | default ('local-lvm:8') }}"
    features:
      - fuse={{ proxmox.lxc.fuse | default ('0') }}
      - keyctl={{ proxmox.lxc.keyctl | default ('0') }}
      - nesting={{ proxmox.lxc.nesting | default ('1') }}
    hostname: "{{ proxmox.lxc.name }}"
    memory: "{{ proxmox.lxc.memory }}"
    nameserver: "{{ proxmox.lxc.nameserver | default ('1.1.1.1') }}"
    # netif: "{'net0':'name=eth0,ip={{ proxmox.lxc.ip }}/24,gw={{ proxmox.lxc.gw }},bridge={{ proxmox.lxc.bridge | default ('vmbr0') }},firewall={{ proxmox.lxc.firewall | default ('1') }}'}"
    netif:
      net0: "name=eth0,ip={{ proxmox.lxc.ip }}/24,gw={{ proxmox.lxc.gw }},bridge={{ proxmox.lxc.bridge | default ('vmbr0') }},firewall={{ proxmox.lxc.firewall | default ('1') }}"
    onboot: "{{ proxmox.lxc.onboot | default ('true') }}"
    ostemplate: "{{ proxmox.lxc.ostemplate | default ('{{ proxmox.lxc.storage_template }}:vztmpl/debian-12-standard_12.7-1_amd64.tar.zst') }}"
    password: "{{ secret.user.lxc.ssh.password }}"
    pubkey: "{{ secret.user.me.ssh.pubkey }}"
    swap: "{{ proxmox.lxc.swap | default ('512') }}"
    tags: "{{ proxmox.lxc.tags }}"
    timezone: "{{ proxmox.lxc.timezone }}"
    unprivileged: "{{ proxmox.lxc.unprivileged | default ('true') }}"
    state: present
  delegate_to: "{{ proxmox.pve.api.host }}"
  
# - name: DÉFINITION DE L'ORDRE DE DÉMARRAGE DU CONTENEUR LXC
#   shell: "pct set {{ proxmox.lxc.vmid }} --startup order={{ proxmox.lxc.startup }}"
#   delegate_to: "{{ proxmox.pve.api.host }}"

# - name: AJOUT DES POINTS DE MONTAGE SUR LE CONTENEUR LXC
#   command: "{{ item }}"
#   with_items:
#     - "pct set {{ proxmox.lxc.vmid }} -mp0 /mnt/storage,mp=/mnt/storage"
#     - "pct set {{ proxmox.lxc.vmid }} -mp1 /mnt/freebox,mp=/mnt/freebox"
#   delegate_to: "{{ proxmox.pve.api.host }}"

- name: DÉMARRAGE DU CONTENEUR LXC
  community.general.proxmox:
    node: "{{ proxmox.pve.api.node }}"
    api_host: "{{ proxmox.pve.api.host }}"
    api_user: "{{ proxmox.pve.api.user }}"
    api_password: "{{ proxmox.pve.api.password }}"
    api_token_id: "{{ proxmox.pve.api.token_id }}"
    api_token_secret: "{{ proxmox.pve.api.token_secret }}"
    vmid: "{{ proxmox.lxc.vmid }}"
    state: "started"
    timeout: 90
  delegate_to: "{{ proxmox.pve.api.host }}"