---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: CONFIGURATION DES PARAMÈTRES RÉGIONAUX
  include_tasks: includes/locales.yml

- name: CRÉATION DE L'UTILISATEUR DÉDIÉ À GEO
  include_tasks: includes/user.yml

- name: CONFIGURATION DES ALIAS BASH
  include_tasks: includes/bash-aliases.yml

- name: INSTALLATION DES PAQUETS PAR DÉFAUT
  include_tasks: includes/packages.yml

- name: INSTALLATION/CONFIGURATION DU MESSAGE OF THE DAY (MOTD)
  include_tasks: includes/motd.yml

- name: INSTALLATION/CONFIGURATION DE zellij
  include_tasks: includes/zellij.yml

- name: INSTALLATION/CONFIGURATION DE apache2
  include_tasks: includes/apache2.yml

- name: INSTALLATION/CONFIGURATION DE java 8
  include_tasks: includes/java.yml