---
- name: CHARGEMENT DES VARIABLES PAR DÉFAUT
  include_vars: defaults/main.yml

- name: INSTALLATION DES PAQUETS
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ default_packages }}"
  become: true
  ignore_errors: true